# Numpy

## Task 1

You should import the necessary libraries. You will use `numpy` and `sys` libraries.


> Don't forget to import `numpy` in the short form.

In [36]:
import numpy as np
import time as time

## Task 2

Create arrays with using Python default syntax and using `numpy`. Also, print the size of the arrays in bytes. You should use `sys` library for this task.

Requirements for arrays:
* length of the array should be `1000`;
* array should contain zeros;
* the second array should be generated by `numpy` library, and should have as little memory as possible.

In [2]:
arr = [0] * 1000

In [3]:
np_arr = np.array(arr)

## Task 3

Write manually a small float array using `numpy` syntax number should be in the range from `0` to `10.0`. Also, you should get the first, the third, and the last elements of the array using multi-indexing.

Requirements:
* length of the array should be from `5` to `10`.

In [4]:
np_arr_f = np.array([1.3, 4.6, 7, 9.2])

## Task 4

You have the array `array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])` using multi-indexing you should summarize a subsequence of an array and get the `27` as the result.

In [15]:
array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])
result = array[0] + array[1] + array[4] + array[7]
result

np.float64(27.0)

## Task 5

You have a matrix `A`:

```python
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])
```

Follow the comments in the next cells and write the code.

In [17]:
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])

### Task 5.1 Find the mean for each column by `x` axis

In [20]:
A.mean(axis=0)

### Task 5.2 Get the standard deviation by `y` axis

In [ ]:
A.mean(axis=1)

### Task 5.3 Get the sum of all elements in `A` by `y` axis

In [23]:
A.sum(axis=1)

### Task 5.4 Get the following result using multi-dim selection:

```python
[
    [1, 6],
    [2, 8],
 ]
```

In [24]:
A[:2, :]

array([[1, 6],
       [2, 8]])

##  Task 5.5. Get the following result using multi-dim selection:
```python
[
    [1, 6],
    [3, 11],
    [1, 7]
 ]
```

In [33]:
A[::2, :]

array([[ 1,  6],
       [ 3, 11],
       [ 1,  7]])

## Task 6

Rewrite Python code to `numpy` code. Also, estimate the time of execution for both implementations.

> Please, note: `unknown_signature` this name just hide the real name of the function, to make the task more complicated.

### Task 6.1

In [47]:
start = time.time()
lst = [i for i in range(1_000_000)]
end = time.time()
print(f"Python time: {end - start}")

Python time: 0.03812217712402344


In [62]:
start = time.time()
numpy_arr = np.arange(1_000_000)
end = time.time()
print(f"Numpy time: {end - start}")

Numpy time: 0.0006809234619140625


### Task 6.2

In [65]:
# Python code
def unknown_signature(vector1, vector2):
    result = 0
    for i in range(len(vector1)):
        result += vector1[i] * vector2[i]
    return result

vector1 = [1, 2, 3]
vector2 = [4, 5, 6]
result = 0

%time unknown_signature(vector1, vector2)

start = time.time()
unknown_signature(vector1, vector2)
end = time.time()

print(f"Python result: {result}")
print(f"Python time: {end - start}")

CPU times: user 4 μs, sys: 0 ns, total: 4 μs
Wall time: 6.91 μs
Python result: 0
Python time: 4.100799560546875e-05


In [64]:
vector3 = np.array([1, 2, 3])
vector4 = np.array([4, 5, 6])
start_time = time.time()
result_numpy = np.dot(vector3, vector4)
numpy_time = time.time() - start_time
print(f"Numpy result: {result_numpy}")
print(f"Numpy time: {numpy_time:.6f}")

Numpy result: 32
Numpy time: 0.000052


### Task 6.3

In [68]:
# Python code
def unknown_signature(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[i])):
            row.append(matrix1[i][j] * matrix2[i][j])
        result.append(row)
    return result

matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]

In [69]:
start_time = time.time()
result_numpy = np.multiply(matrix1, matrix2)
numpy_time = time.time() - start_time
print("Numpy result:")
print(result_numpy)
print(f"Numpy time: {numpy_time:.6f}")

NumPy implementation result:
[[ 5 12]
 [21 32]]
NumPy implementation took: 0.000075 seconds


### Task 6.4

In [ ]:
# Python code
def unknown_signature(lst):
    total = 0
    for num in lst:
        total += num
    result = total / len(lst)
    return result

lst = [1, 2, 3, 4, 5]

In [74]:
start_time = time.time()
result_numpy = np.mean([lst])
numpy_time = time.time() - start_time
print("Numpy result:", result_numpy)
print(f"Numpy time: {numpy_time:.6f}")

Numpy result: 1.2
Numpy time: 0.000102


## Task 7

Rewrite Python code to `numpy` code (Masks).

### Task 7.1

In [72]:
# Python code
def unknown_signature(lst, mask, new_value):
    for i in range(len(lst)):
        if mask[i]:
            lst[i] = new_value

lst = [1, 2, 3, 4, 5]
mask = [True, False, True, False, True]
new_value = 0
unknown_signature(lst, mask, new_value)
lst

[0, 2, 0, 4, 0]

In [71]:
lst_np = np.array([1, 2, 3, 4, 5])
mask_np = np.array([True, False, True, False, True])
new_value = 0

lst_np[mask_np] = new_value
print(lst_np)

[0 2 0 4 0]


### Task 7.2

In [33]:
# Python code
def unknown_signature(lst1, lst2):
    bitwise_complement = [~x for x in lst1]
    bitwise_and = [x & y for x, y in zip(lst1, lst2)]
    bitwise_or = [x | y for x, y in zip(lst1, lst2)]
    return bitwise_complement, bitwise_and, bitwise_or

list1 = [5, 2, 7, 4, 9]
list2 = [3, 6, 1, 8, 10]
result_bitwise_complement, result_bitwise_and, result_bitwise_or = unknown_signature(list1, list2)
result_bitwise_complement, result_bitwise_and, result_bitwise_or

In [75]:
array1 = np.array([5, 2, 7, 4, 9])
array2 = np.array([3, 6, 1, 8, 10])

bitwise_complement = ~array1
bitwise_and = array1 & array2
bitwise_or = array1 | array2

print("Bitwise complement:", bitwise_complement)
print("Bitwise and:", bitwise_and)
print("Bitwise or:", bitwise_or)

Bitwise complement: [ -6  -3  -8  -5 -10]
Bitwise and: [1 2 1 0 8]
Bitwise or: [ 7  6  7 12 11]


### Task 7.3 Optional

In [34]:
# Python code
def unknown_signature(lst):
    result = []
    for num in lst:
        if num % 2 == 0 and (num % 3 == 0 or num > 10):
            modified_num = (num ^ 7) + 2
            result.append(modified_num)
    return result

my_list = [6, 9, 12, 14, 17, 20]
result_python_style = unknown_signature(my_list)
result_python_style

[3, 13, 11, 21]

In [35]:
# write your numpy code here